apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: deviceshifu-asd
    workspace_id: "f787e5f5-f42c-42d5-89f3-0fd99528c4ce"
  name: deviceshifu-asd-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: "TAS-WS-R0020"
    driverImage:
  instructions: |
    instructions:
      th:
      Temperature:
      Humidity:
  telemetries: |
    telemetries:
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-asd
    workspace_id: "f787e5f5-f42c-42d5-89f3-0fd99528c4ce"
  name: deviceshifu-asd-service
  namespace: deviceshifu
spec:
  ports:
  - name: http-service
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-asd-deployment
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-asd
    workspace_id: "f787e5f5-f42c-42d5-89f3-0fd99528c4ce"
  name: deviceshifu-asd-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-asd-deployment
  template:
    metadata:
      labels:
        app: deviceshifu-asd-deployment
    spec:
      containers:
        - image: edgehub/deviceshifu-http-http:v0.64.0
          name: deviceshifu-http
          ports:
          - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: /etc/edgedevice/config
              readOnly: true
          env:
          - name: EDGEDEVICE_NAME
            value: "deviceshifu-asd-edgedevice"
          - name: EDGEDEVICE_NAMESPACE
            value: "devices"
        - name: shifu-driver
          image: edgenesis/modbus-temperature-humdity:v0.0.1
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: DEVICE_ADDRESS
              value: "1.2.3.4:1234"
      volumes:
        - name: deviceshifu-config
          configMap:
            name: deviceshifu-asd-configmap
      serviceAccountName: edgedevice-sa
---
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  labels:
    app: deviceshifu-asd
    workspace_id: "f787e5f5-f42c-42d5-89f3-0fd99528c4ce"
  name: deviceshifu-asd-edgedevice
  namespace: devices
spec:
  sku: "TAS-WS-R0020"
  connection: "Ethernet"
  address: "0.0.0.0:9090"
  protocol: "HTTP"
